### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated 

### ISSUE THREAD

**Issue by sudajiaqi** [GodMoonLight/moon-style#40]
### What happened?

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.godmoonlight.moonstyle.actions.ConverterToAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.godmoonlight.moonstyle]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

### Steps to reproduce

when use this plugin

### Gradle IntelliJ Plugin version

1.16.0

### Gradle version

8.2.1

### Operating System

macOS

**Comment by sudajiaqi** [comment]
resolve in
#41
